"""
=============================================================================
Project Ghost Burn v2 — Data Simulation Engine
=============================================================================
Generates a synthetic dataset mimicking Databricks' `system.billing.usage`
table schema (2026 spec). Designed for Google Colab + BigQuery Sandbox.

Author:  Wyatt Barandino — Data Analyst
Version: 2.0.0 — March 2026
License: MIT

DISCLAIMER:
    All data generated by this script is 100% synthetic. No real Databricks
    billing data, customer information, workspace configurations, or
    proprietary schemas were used at any point. The system.billing.usage
    schema is modeled exclusively from publicly available Databricks
    documentation. This project is entirely independent and is not affiliated
    with, endorsed by, sponsored by, or produced in partnership with
    Databricks, Inc. No confidential or proprietary information of Databricks
    or any of its customers was accessed, used, or referenced.

USAGE:
    Run all cells in Google Colab or locally with Python 3.9+.
    Output: `ghost_burn_billing.csv`
    Upload to BigQuery Sandbox dataset: `ghost_burn.billing_usage`

NOTE ON estimated_cost_usd:
    This column is a simulation convenience field derived from
    usage_quantity × SKU rate. It does NOT exist in the real
    system.billing.usage schema. In a production Databricks environment,
    cost is derived by joining system.billing.usage with
    system.billing.list_prices. See DATABRICKS_MIGRATION.md for details.
=============================================================================
"""

# ── CELL 1: IMPORTS & CONFIG ─────────────────────────────────────────────────

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import uuid
import json
import warnings
import json

class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, (np.integer,)):
            return int(obj)
        if isinstance(obj, (np.floating,)):
            return float(obj)
        return super().default(obj)
import os


class NumpyEncoder(json.JSONEncoder):
    """Handles numpy scalar types for JSON serialization."""
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return super().default(obj)

def jdumps(d):
    return json.dumps(d, cls=NumpyEncoder)

warnings.filterwarnings("ignore")
np.random.seed(2026)

# ── Configuration ─────────────────────────────────────────────────────────────

CONFIG = {
    "start_date":            "2026-01-01",
    "end_date":              "2026-04-01",   # 90 days — one full quarter
    "num_workspaces":        8,
    "records_per_day_base":  120,
    "output_file":           "ghost_burn_billing.csv",
}

# ── 2026 Databricks SKU Catalog ───────────────────────────────────────────────
# Weights reflect 2026's serverless-heavy reality.
# GPU and serverless SKUs represent a larger share than in prior years.

SKU_CATALOG = {
    # Interactive compute
    "STANDARD_ALL_PURPOSE_COMPUTE":    {"rate": 0.40, "weight": 0.10, "category": "Interactive"},
    "PREMIUM_ALL_PURPOSE_COMPUTE":     {"rate": 0.55, "weight": 0.07, "category": "Interactive"},
    # Production workloads
    "JOBS_COMPUTE":                    {"rate": 0.15, "weight": 0.16, "category": "Production"},
    "JOBS_SERVERLESS_COMPUTE":         {"rate": 0.20, "weight": 0.13, "category": "Production"},
    # BI / SQL
    "SQL_PRO_COMPUTE":                 {"rate": 0.22, "weight": 0.06, "category": "BI/SQL"},
    "SERVERLESS_SQL_COMPUTE":          {"rate": 0.35, "weight": 0.09, "category": "BI/SQL"},
    # AI / ML — higher weights in 2026
    "SERVERLESS_REAL_TIME_INFERENCE":  {"rate": 0.65, "weight": 0.09, "category": "AI/ML"},
    "GPU_SERVERLESS_COMPUTE":          {"rate": 1.20, "weight": 0.06, "category": "AI/ML"},
    "FOUNDATION_MODEL_TRAINING":       {"rate": 2.50, "weight": 0.03, "category": "AI/ML"},
    "VECTOR_SEARCH_COMPUTE":           {"rate": 0.30, "weight": 0.06, "category": "AI/ML"},
    # Storage & governance
    "DELTA_STORAGE":                   {"rate": 0.02, "weight": 0.08, "category": "Storage"},
    "UNITY_CATALOG_COMPUTE":           {"rate": 0.10, "weight": 0.07, "category": "Governance"},
}

# ── GPU Instance Catalog ──────────────────────────────────────────────────────
# Maps GPU SKUs to correct AWS instance families with hardware specs.
# Used exclusively for AI/ML category metadata — no storage-optimized
# instances (i3, m5, r5) will appear in GPU billing records.

GPU_INSTANCE_CATALOG = {
    "p4d.24xlarge": {
        "gpu_count": 8, "gpu_type": "A100",
        "gpu_memory_gb": 320, "cost_multiplier": 3.2,
        "use_case": "large_scale_training",
    },
    "g5.12xlarge": {
        "gpu_count": 4, "gpu_type": "A10G",
        "gpu_memory_gb": 96,  "cost_multiplier": 1.0,
        "use_case": "fine_tuning_inference",
    },
    "g5.xlarge": {
        "gpu_count": 1, "gpu_type": "A10G",
        "gpu_memory_gb": 24,  "cost_multiplier": 0.4,
        "use_case": "inference_serving",
    },
    "g4dn.xlarge": {
        "gpu_count": 1, "gpu_type": "T4",
        "gpu_memory_gb": 16,  "cost_multiplier": 0.3,
        "use_case": "lightweight_inference",
    },
    "p3.2xlarge": {
        "gpu_count": 1, "gpu_type": "V100",
        "gpu_memory_gb": 16,  "cost_multiplier": 0.6,
        "use_case": "training_experimentation",
    },
}

# Standard (non-GPU) instance types for non-AI workloads
STANDARD_INSTANCE_TYPES = [
    "m5.2xlarge", "m5.4xlarge", "r5.xlarge",
    "r5.2xlarge", "c5.4xlarge", "c5.9xlarge",
]

# ── Workspace Profiles ────────────────────────────────────────────────────────
# Named after recognizable Databricks customer archetypes.
# These map to Databricks' actual verticals: FSI, retail, healthcare, etc.

WORKSPACES = {
    "ws-fsi-trading-001": {
        "team": "Data Engineering",
        "industry": "Financial Services",
        "env": "production",
        "budget_daily_dbu": 850,
        "description": "Real-time trading analytics and risk data pipelines",
    },
    "ws-retail-forecast-002": {
        "team": "ML Platform",
        "industry": "Retail",
        "env": "production",
        "budget_daily_dbu": 650,
        "description": "Demand forecasting and inventory optimization models",
    },
    "ws-health-analytics-003": {
        "team": "Analytics",
        "industry": "Healthcare",
        "env": "development",
        "budget_daily_dbu": 320,
        "description": "Clinical outcomes analysis and population health reporting",
    },
    "ws-prod-bi-004": {
        "team": "BI & Reporting",
        "industry": "Enterprise",
        "env": "production",
        "budget_daily_dbu": 420,
        "description": "Executive dashboards and cross-functional reporting",
    },
    "ws-sandbox-ds-005": {
        "team": "Data Science",
        "industry": "Cross-industry",
        "env": "sandbox",
        "budget_daily_dbu": 210,
        "description": "Exploratory analysis and model experimentation",
    },
    "ws-ai-serving-006": {
        "team": "AI Serving",
        "industry": "Tech",
        "env": "production",
        "budget_daily_dbu": 550,
        "description": "Real-time model serving and vector search infrastructure",
    },
    "ws-staging-007": {
        "team": "Platform Ops",
        "industry": "Internal",
        "env": "staging",
        "budget_daily_dbu": 260,
        "description": "Pre-production validation and integration testing",
    },
    "ws-zombie-008": {
        "team": "Legacy Migration",
        "industry": "Internal",
        "env": "production",
        "budget_daily_dbu": 160,
        "description": "Decommissioned migration project — pending cleanup",
    },
}


# ── CELL 2: ANOMALY INJECTION ENGINE ─────────────────────────────────────────

class AnomalyEngine:
    """
    Injects five realistic FinOps anomalies into the billing dataset.
    Each anomaly mirrors a documented real-world Databricks cost incident.

    Anomaly types:
        1. Zombie Cluster          — 24/7 idle compute, auto-termination disabled
        2. Serverless SQL Spike    — Runaway dashboard refresh, 10x baseline
        3. GPU Overprovisioning    — p4d.24xlarge at 25% utilization
        4. Weekend Dev Waste       — Interactive clusters with no off-hours policy
        5. Runaway DLT Pipeline    — Continuous mode on a batch workload
    """

    @staticmethod
    def inject_zombie_cluster(df: pd.DataFrame) -> pd.DataFrame:
        """
        ANOMALY 1: Zombie Cluster
        ─────────────────────────
        A legacy all-purpose cluster in ws-zombie-008 runs 24/7 with no
        associated job activity. Simulates a forgotten dev cluster that was
        never terminated after a migration project ended.

        Detection signals:
          - job_id: null (no productive work)
          - autotermination_minutes: 0 (governance violation — policy disabled)
          - usage_cv_pct < 10% (suspiciously flat hourly consumption)
          - total_hours_active > 300 over 90 days
        """
        print("  💀 Injecting Anomaly 1: Zombie Cluster (ws-zombie-008)...")

        date_range = pd.date_range(CONFIG["start_date"], CONFIG["end_date"], freq="h")[:-1]
        records = []

        for ts in date_range:
            records.append({
                "workspace_id":     "ws-zombie-008",
                "sku_name":         "PREMIUM_ALL_PURPOSE_COMPUTE",
                "usage_start_time": ts,
                "usage_end_time":   ts + timedelta(hours=1),
                "usage_quantity":   round(np.random.normal(4.0, 0.08), 4),  # flat → low CV
                "usage_metadata":   jdumps({
                    "cluster_id":             "zombie-clstr-0xDEAD",
                    "cluster_name":           "legacy-migration-jan-temp",
                    "job_id":                 None,       # null job_id = zombie signal
                    "notebook_id":            None,
                    "cluster_source":         "UI",
                    "instance_type":          "m5.4xlarge",
                    "driver_node_type":       "m5.4xlarge",
                    "autotermination_minutes": 0,          # disabled = governance violation
                    "spark_version":          "13.3.x-scala2.12",
                    "data_security_mode":     "NONE",      # Unity Catalog not enforced
                }),
            })

        zombie_df = pd.DataFrame(records)
        print(f"     ✓ {len(zombie_df):,} zombie records injected (90-day continuous)")
        return pd.concat([df, zombie_df], ignore_index=True)

    @staticmethod
    def inject_serverless_spike(df: pd.DataFrame) -> pd.DataFrame:
        """
        ANOMALY 2: Serverless SQL Spike
        ────────────────────────────────
        A runaway dashboard refresh in ws-prod-bi-004 triggers a 10x spike
        in Serverless SQL compute over a 72-hour window (Feb 10–13).
        Simulates an unoptimized Tableau extract refreshing every 5 minutes.

        Detection signals:
          - 72hr window with usage 8–12x above workspace baseline
          - query_count_hourly: 200–400 (vs. normal 5–80)
          - query_source: tableau_extract_refresh
        """
        print("  📈 Injecting Anomaly 2: Serverless SQL Spike (ws-prod-bi-004, Feb 10–13)...")

        spike_hours = pd.date_range("2026-02-10", "2026-02-13", freq="h")[:-1]
        records = []

        for ts in spike_hours:
            records.append({
                "workspace_id":     "ws-prod-bi-004",
                "sku_name":         "SERVERLESS_SQL_COMPUTE",
                "usage_start_time": ts,
                "usage_end_time":   ts + timedelta(hours=1),
                "usage_quantity":   round(np.random.normal(48.0, 7.0), 4),  # 10x normal
                "usage_metadata":   jdumps({
                    "cluster_id":          None,
                    "warehouse_id":        "sql-wh-bi-auto-004",
                    "warehouse_name":      "bi_reporting_serverless",
                    "job_id":              None,
                    "query_source":        "tableau_extract_refresh",
                    "query_count_hourly":  int(np.random.randint(200, 400)),
                    "endpoint_name":       "dashboard-refresh-prod",
                    "auto_stop_mins":      0,          # auto-stop disabled
                }),
            })

        spike_df = pd.DataFrame(records)
        print(f"     ✓ {len(spike_df):,} spike records injected (72-hour window)")
        return pd.concat([df, spike_df], ignore_index=True)

    @staticmethod
    def inject_gpu_overprovisioning(df: pd.DataFrame) -> pd.DataFrame:
        """
        ANOMALY 3: GPU Overprovisioning
        ────────────────────────────────
        The ML Platform team (ws-retail-forecast-002) runs nightly fine-tuning
        jobs on p4d.24xlarge (8x A100, 320GB) when g5.12xlarge (4x A10G, 96GB)
        would suffice. The job runs 4 hours/night at only 25% GPU utilization.

        Detection signals:
          - gpu_utilization_pct: 10–30% (critically underutilized)
          - instance_type: p4d.24xlarge (A100 — overkill for this workload)
          - Consistent nightly 4-hour window
          - Right-sizing to g5.12xlarge saves ~50% cost

        Right-sizing note:
          This recommendation assumes the fine-tuning workload fits within
          g5.12xlarge memory constraints (96GB vs 320GB on p4d.24xlarge).
          Validate with a test run before production deployment.
        """
        print("  🔥 Injecting Anomaly 3: GPU Overprovisioning (ws-retail-forecast-002)...")

        date_range = pd.date_range(CONFIG["start_date"], CONFIG["end_date"], freq="D")
        gpu_instance = GPU_INSTANCE_CATALOG["p4d.24xlarge"]
        records = []

        for day in date_range:
            job_start = day + timedelta(hours=2)  # 2 AM nightly job
            for hour_offset in range(4):           # 4-hour job window
                ts = job_start + timedelta(hours=hour_offset)
                records.append({
                    "workspace_id":     "ws-retail-forecast-002",
                    "sku_name":         "GPU_SERVERLESS_COMPUTE",
                    "usage_start_time": ts,
                    "usage_end_time":   ts + timedelta(hours=1),
                    "usage_quantity":   round(np.random.normal(20.0, 1.5), 4),
                    "usage_metadata":   jdumps({
                        "cluster_id":          "gpu-finetune-nightly",
                        "job_id":              "job-demand-finetune-v4",
                        "job_name":            "nightly_demand_forecast_finetune",
                        "instance_type":       "p4d.24xlarge",       # GPU-correct instance
                        "gpu_count":           gpu_instance["gpu_count"],
                        "gpu_type":            gpu_instance["gpu_type"],
                        "gpu_memory_gb":       gpu_instance["gpu_memory_gb"],
                        "gpu_utilization_pct": round(np.random.uniform(10, 30), 1),  # underutilized
                        "recommended_instance": "g5.12xlarge",        # right-size target
                        "spark_version":       "14.3.x-gpu-ml-scala2.12",
                    }),
                })

        gpu_df = pd.DataFrame(records)
        print(f"     ✓ {len(gpu_df):,} GPU records injected (nightly 4hr window, 90 days)")
        return pd.concat([df, gpu_df], ignore_index=True)

    @staticmethod
    def inject_weekend_waste(df: pd.DataFrame) -> pd.DataFrame:
        """
        ANOMALY 4: Weekend Dev Waste
        ─────────────────────────────
        Interactive clusters in ws-sandbox-ds-005 and ws-health-analytics-003
        run through weekends without an off-hours lifecycle policy.
        Developers leave clusters running Friday evening through Monday morning.

        Detection signals:
          - usage_start_time.weekday() in [5, 6] (Saturday, Sunday)
          - sku_name: STANDARD_ALL_PURPOSE_COMPUTE
          - env: sandbox / development (non-production)
          - No weekend_policy tag in metadata
        """
        print("  🗓️  Injecting Anomaly 4: Weekend Dev Waste (sandbox + health workspaces)...")

        target_workspaces = ["ws-sandbox-ds-005", "ws-health-analytics-003"]
        date_range = pd.date_range(CONFIG["start_date"], CONFIG["end_date"], freq="h")[:-1]
        records = []

        for ts in date_range:
            if ts.weekday() not in [5, 6]:  # Saturday=5, Sunday=6
                continue
            for ws_id in target_workspaces:
                if np.random.random() > 0.75:  # not every hour — realistic gaps
                    continue
                records.append({
                    "workspace_id":     ws_id,
                    "sku_name":         "STANDARD_ALL_PURPOSE_COMPUTE",
                    "usage_start_time": ts,
                    "usage_end_time":   ts + timedelta(hours=1),
                    "usage_quantity":   round(np.random.normal(2.5, 0.4), 4),
                    "usage_metadata":   jdumps({
                        "cluster_id":              f"dev-clstr-{ws_id[-3:]}",
                        "cluster_name":            f"ds-interactive-{ws_id[-3:]}",
                        "job_id":                  None,
                        "instance_type":           "m5.2xlarge",
                        "autotermination_minutes":  240,   # 4hr — too long for dev
                        "weekend_policy":           None,   # no weekend policy = waste signal
                        "cluster_source":           "UI",
                        "spark_version":            "14.3.x-scala2.12",
                    }),
                })

        weekend_df = pd.DataFrame(records)
        print(f"     ✓ {len(weekend_df):,} weekend waste records injected")
        return pd.concat([df, weekend_df], ignore_index=True)

    @staticmethod
    def inject_dlt_pipeline_waste(df: pd.DataFrame) -> pd.DataFrame:
        """
        ANOMALY 5: Runaway DLT Pipeline (NEW in v2)
        ─────────────────────────────────────────────
        A Delta Live Tables pipeline in ws-fsi-trading-001 was configured in
        CONTINUOUS mode for a workload that only needs hourly batch triggers.
        Continuous mode keeps the pipeline cluster alive permanently, consuming
        DBUs even when no new data arrives — a known DLT billing antipattern.

        Detection signals:
          - pipeline_mode: CONTINUOUS (should be TRIGGERED for batch data)
          - sku_name: JOBS_SERVERLESS_COMPUTE
          - Consistent 24/7 usage pattern with periodic data_processed_gb: 0
          - No trigger_interval in metadata (continuous has no trigger)

        Fix: Switch pipeline to TRIGGERED mode with 60-minute schedule.
        Estimated savings: ~60% reduction in DLT compute hours.
        """
        print("  🔄 Injecting Anomaly 5: Runaway DLT Pipeline (ws-fsi-trading-001)...")

        date_range = pd.date_range(CONFIG["start_date"], CONFIG["end_date"], freq="h")[:-1]
        records = []

        for ts in date_range:
            # DLT continuous pipeline — always running, but data only arrives business hours
            data_arriving = (8 <= ts.hour <= 18) and (ts.weekday() < 5)
            data_processed = round(np.random.uniform(2.0, 8.0), 2) if data_arriving else 0.0

            records.append({
                "workspace_id":     "ws-fsi-trading-001",
                "sku_name":         "JOBS_SERVERLESS_COMPUTE",
                "usage_start_time": ts,
                "usage_end_time":   ts + timedelta(hours=1),
                "usage_quantity":   round(np.random.normal(3.5, 0.3), 4),  # flat 24/7
                "usage_metadata":   jdumps({
                    "cluster_id":         "dlt-pipeline-risk-001",
                    "pipeline_id":        "pipe-risk-factor-etl",
                    "pipeline_name":      "risk_factor_bronze_to_silver",
                    "pipeline_mode":      "CONTINUOUS",     # antipattern — should be TRIGGERED
                    "trigger_interval":   None,             # no trigger = continuous signal
                    "data_processed_gb":  data_processed,  # 0 when no data = wasted hours
                    "job_id":             "dlt-job-risk-001",
                    "target_table":       "silver.risk_factors_hourly",
                    "spark_version":      "14.3.x-scala2.12",
                }),
            })

        dlt_df = pd.DataFrame(records)
        print(f"     ✓ {len(dlt_df):,} DLT pipeline records injected (90-day continuous)")
        return pd.concat([df, dlt_df], ignore_index=True)


# ── CELL 3: BASELINE GENERATOR ───────────────────────────────────────────────

def _build_metadata(sku: str, workspace_id: str, timestamp: datetime) -> dict:
    """
    Constructs realistic usage_metadata JSON for each SKU type.
    GPU SKUs exclusively use GPU_INSTANCE_CATALOG — never storage-optimized
    instance types. This matches the real Databricks billing schema behavior.
    """
    category = SKU_CATALOG[sku]["category"]

    if category == "AI/ML":
        # GPU workloads: always use GPU-appropriate instance types
        gpu_instance_name = np.random.choice(list(GPU_INSTANCE_CATALOG.keys()))
        gpu_instance = GPU_INSTANCE_CATALOG[gpu_instance_name]
        base_meta = {
            "cluster_id":          f"clstr-{workspace_id[-3:]}-{sku[:6].lower()}",
            "instance_type":       gpu_instance_name,          # GPU-correct instance
            "gpu_count":           gpu_instance["gpu_count"],
            "gpu_type":            gpu_instance["gpu_type"],
            "gpu_memory_gb":       gpu_instance["gpu_memory_gb"],
            "gpu_utilization_pct": round(np.random.uniform(40, 85), 1),  # healthy utilization
            "job_id":              f"ml-job-{np.random.randint(100, 999)}",
            "model_name":          np.random.choice([
                "churn_predictor_v3", "demand_forecast_v2",
                "rag_pipeline_prod", "risk_scorer_v1",
            ]),
            "spark_version":       "14.3.x-gpu-ml-scala2.12",
        }

    elif category == "Production":
        base_meta = {
            "cluster_id":   f"clstr-{workspace_id[-3:]}-jobs",
            "instance_type": np.random.choice(STANDARD_INSTANCE_TYPES),
            "job_id":        f"job-{np.random.randint(1000, 9999)}",
            "job_name":      np.random.choice([
                "etl_daily_ingest", "dlt_pipeline_silver",
                "feature_store_refresh", "medallion_gold_transform",
                "quality_checks_daily", "risk_factor_etl",
            ]),
            "run_id":        f"run-{np.random.randint(10000, 99999)}",
            "spark_version": "14.3.x-scala2.12",
        }

    elif category == "BI/SQL":
        base_meta = {
            "warehouse_id":        f"sql-wh-{workspace_id[-3:]}",
            "warehouse_name":      np.random.choice([
                "reporting_wh", "adhoc_wh", "exec_dashboard_wh", "genie_wh",
            ]),
            "query_count_hourly":  int(np.random.randint(5, 80)),
            "query_source":        np.random.choice([
                "tableau", "power_bi", "databricks_sql", "genie", "sdk",
            ]),
            "auto_stop_mins":      np.random.choice([10, 20, 30]),
        }

    elif category == "Interactive":
        base_meta = {
            "cluster_id":              f"clstr-{workspace_id[-3:]}-interactive",
            "instance_type":           np.random.choice(STANDARD_INSTANCE_TYPES),
            "autotermination_minutes": np.random.choice([30, 60, 120]),
            "cluster_source":          np.random.choice(["UI", "API", "JOB"]),
            "data_security_mode":      "USER_ISOLATION",
            "spark_version":           "14.3.x-scala2.12",
        }

    elif category == "Governance":
        base_meta = {
            "catalog_name": np.random.choice(["main", "analytics", "ml_features", "raw"]),
            "operation":    np.random.choice([
                "lineage_capture", "audit_log_write", "acl_check", "tag_propagation",
            ]),
        }

    else:  # Storage
        base_meta = {
            "storage_gb":  round(np.random.uniform(10, 500), 2),
            "table_count": int(np.random.randint(5, 200)),
            "catalog_name": np.random.choice(["main", "analytics", "ml_features"]),
        }

    return base_meta


def generate_baseline_billing() -> pd.DataFrame:
    """
    Generates the clean baseline billing records for all 8 workspaces.
    Applies business-hours weighting and weekend reduction for non-production
    workspaces to create realistic temporal patterns.
    """
    print("\n📊 Generating baseline billing records...")

    sku_names    = list(SKU_CATALOG.keys())
    sku_weights  = [SKU_CATALOG[s]["weight"] for s in sku_names]
    sku_weights  = [w / sum(sku_weights) for w in sku_weights]  # normalize

    date_range = pd.date_range(CONFIG["start_date"], CONFIG["end_date"], freq="h")[:-1]
    records    = []

    for ws_id, ws_info in WORKSPACES.items():
        daily_budget = ws_info["budget_daily_dbu"]
        ws_records   = 0

        for ts in date_range:
            hour        = ts.hour
            is_weekend  = ts.weekday() >= 5
            is_prod     = ws_info["env"] == "production"

            # Business-hours weighting (UTC — approximates US Eastern business hours)
            if 13 <= hour <= 22:       # 8 AM–5 PM ET
                hour_weight = np.random.uniform(1.0, 1.6)
            elif 0 <= hour <= 5:       # overnight
                hour_weight = np.random.uniform(0.05, 0.2)
            else:
                hour_weight = np.random.uniform(0.3, 0.7)

            # Weekend reduction for non-production workspaces
            if is_weekend and not is_prod:
                hour_weight *= 0.12

            # Probabilistic record generation
            if np.random.random() > min(hour_weight, 0.95):
                continue

            sku         = np.random.choice(sku_names, p=sku_weights)
            hourly_budget = daily_budget / 24
            usage_qty   = round(
                max(0.01, hourly_budget * hour_weight * np.random.lognormal(0, 0.35)),
                4
            )
            metadata    = _build_metadata(sku, ws_id, ts)

            records.append({
                "workspace_id":     ws_id,
                "sku_name":         sku,
                "usage_start_time": ts,
                "usage_end_time":   ts + timedelta(hours=1),
                "usage_quantity":   usage_qty,
                "usage_metadata":   jdumps(metadata),
            })
            ws_records += 1

        print(f"   ✓ {ws_id}: {ws_records:,} records")

    df = pd.DataFrame(records)
    print(f"\n   Baseline total: {len(df):,} records across {len(WORKSPACES)} workspaces")
    return df


# ── CELL 4: MAIN EXECUTION ───────────────────────────────────────────────────

def main():
    """
    Main pipeline: Generate baseline → Inject anomalies → Enrich → Export
    """
    print("=" * 72)
    print("  PROJECT GHOST BURN v2 — Data Simulation Engine")
    print("  Simulating Databricks system.billing.usage (2026 Schema)")
    print("  Audit Window: Q1 2026 — 90 days (January 1 → April 1)")
    print("=" * 72)

    # Step 1: Generate baseline
    df = generate_baseline_billing()

    # Step 2: Inject all five anomalies
    print("\n⚡ Injecting anomalies...")
    engine = AnomalyEngine()
    df = engine.inject_zombie_cluster(df)
    df = engine.inject_serverless_spike(df)
    df = engine.inject_gpu_overprovisioning(df)
    df = engine.inject_weekend_waste(df)
    df = engine.inject_dlt_pipeline_waste(df)

    # Step 3: Sort and assign usage_record_id (UUID4 — matches real schema format)
    print("\n📊 Enriching dataset...")
    df = df.sort_values("usage_start_time").reset_index(drop=True)
    df.insert(0, "usage_record_id", [str(uuid.uuid4()) for _ in range(len(df))])

    # Step 4: Derive estimated_cost_usd
    # NOTE: This column is a simulation convenience field.
    # In real system.billing.usage, cost requires joining system.billing.list_prices.
    # See DATABRICKS_MIGRATION.md for the production query pattern.
    df["estimated_cost_usd"] = df.apply(
        lambda row: round(
            row["usage_quantity"] * SKU_CATALOG.get(row["sku_name"], {}).get("rate", 0.20),
            4
        ),
        axis=1
    )

    # Step 5: Summary statistics
    total_cost  = df["estimated_cost_usd"].sum()
    total_dbus  = df["usage_quantity"].sum()

    print(f"\n{'─' * 60}")
    print(f"  Total records:        {len(df):>12,}")
    print(f"  Date range:           {df['usage_start_time'].min().date()} → "
          f"{df['usage_start_time'].max().date()}")
    print(f"  Total DBUs:           {total_dbus:>12,.1f}")
    print(f"  Total Est. Cost:      ${total_cost:>11,.2f}")
    print(f"  Unique workspaces:    {df['workspace_id'].nunique():>12}")
    print(f"  Unique SKUs:          {df['sku_name'].nunique():>12}")
    print(f"{'─' * 60}")

    # Step 6: Anomaly cost summary
    zombie_cost = df[
        (df["workspace_id"] == "ws-zombie-008") &
        (df["sku_name"] == "PREMIUM_ALL_PURPOSE_COMPUTE")
    ]["estimated_cost_usd"].sum()

    spike_cost = df[
        (df["workspace_id"] == "ws-prod-bi-004") &
        (df["usage_start_time"] >= "2026-02-10") &
        (df["usage_start_time"] <  "2026-02-13") &
        (df["sku_name"] == "SERVERLESS_SQL_COMPUTE")
    ]["estimated_cost_usd"].sum()

    gpu_waste = df[
        (df["sku_name"] == "GPU_SERVERLESS_COMPUTE") &
        (df["workspace_id"] == "ws-retail-forecast-002")
    ]["estimated_cost_usd"].sum() * 0.50  # 50% savings from right-sizing

    weekend_cost = df[
        (df["workspace_id"].isin(["ws-sandbox-ds-005", "ws-health-analytics-003"])) &
        (df["usage_start_time"].dt.weekday >= 5) &
        (df["sku_name"] == "STANDARD_ALL_PURPOSE_COMPUTE")
    ]["estimated_cost_usd"].sum()

    dlt_waste = df[
        (df["workspace_id"] == "ws-fsi-trading-001") &
        (df["sku_name"] == "JOBS_SERVERLESS_COMPUTE")
    ]["estimated_cost_usd"].sum() * 0.60  # 60% savings from TRIGGERED mode

    total_waste     = zombie_cost + spike_cost + gpu_waste + weekend_cost + dlt_waste
    annual_waste    = total_waste * (365 / 90)
    annual_savings  = annual_waste * 0.97  # 97% recovery rate with automated policies

    print(f"\n🚨 ANOMALY COST SUMMARY — Recoverable Waste (90-day audit)")
    print(f"{'─' * 60}")
    print(f"  💀 Zombie Cluster:          ${zombie_cost:>10,.2f}")
    print(f"  📈 Serverless SQL Spike:    ${spike_cost:>10,.2f}")
    print(f"  🔥 GPU Right-sizing (50%):  ${gpu_waste:>10,.2f}")
    print(f"  🗓️  Weekend Dev Waste:       ${weekend_cost:>10,.2f}")
    print(f"  🔄 DLT Pipeline (60%):      ${dlt_waste:>10,.2f}")
    print(f"{'─' * 60}")
    print(f"  💰 TOTAL RECOVERABLE (90d): ${total_waste:>10,.2f}")
    print(f"  📅 ANNUALIZED PROJECTION:   ${annual_waste:>10,.2f}")
    print(f"  ✅ NET ANNUAL SAVINGS:       ${annual_savings:>10,.2f}")
    print(f"  📉 % of Total Spend:        {total_waste / total_cost * 100:.1f}%")
    print(f"{'─' * 60}")

    # Step 7: Export
    output_path = CONFIG["output_file"]
    df.to_csv(output_path, index=False)
    file_kb = os.path.getsize(output_path) / 1024

    print(f"\n✅ Dataset exported: {output_path}")
    print(f"   Records: {len(df):,} | Size: {file_kb:.0f} KB")
    print(f"\n📋 NEXT STEP: Upload to BigQuery")
    print(f"   Dataset: ghost_burn | Table: billing_usage | Schema: auto-detect ✓")
    print(f"\n⚠️  NOTE: estimated_cost_usd is a simulation convenience column.")
    print(f"   See DATABRICKS_MIGRATION.md for the production list_prices join pattern.")

    return df


# ── RUN ───────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    df = main()
